export const tasks = [
    { "id": 1, "title": "Wake up early" },
    { "id": 2, "title": "Drink a glass of water" },
    { "id": 3, "title": "Go for a morning walk" },
    { "id": 4, "title": "Meditate for 10 minutes" },
    { "id": 5, "title": "Read 20 pages of a book" },
    { "id": 6, "title": "Write in a journal" },
    { "id": 7, "title": "Practice English speaking" },
    { "id": 8, "title": "Learn 10 new English words" },
    { "id": 9, "title": "Solve 2 LeetCode problems" },
    { "id": 10, "title": "Review DSA notes" },
    { "id": 11, "title": "Watch a React tutorial" },
    { "id": 12, "title": "Build a React component" },
    { "id": 13, "title": "Practice JavaScript ES6" },
    { "id": 14, "title": "Learn TypeScript basics" },
    { "id": 15, "title": "Read FastAPI documentation" },
    { "id": 16, "title": "Create a REST API endpoint" },
    { "id": 17, "title": "Learn Django models" },
    { "id": 18, "title": "Practice SQL queries" },
    { "id": 19, "title": "Normalize a database schema" },
    { "id": 20, "title": "Design an ER diagram" },
    { "id": 21, "title": "Learn Git branching" },
    { "id": 22, "title": "Commit project changes" },
    { "id": 23, "title": "Push code to GitHub" },
    { "id": 24, "title": "Review pull requests" },
    { "id": 25, "title": "Update portfolio website" },
    { "id": 26, "title": "Write project documentation" },
    { "id": 27, "title": "Fix a UI bug" },
    { "id": 28, "title": "Optimize CSS layout" },
    { "id": 29, "title": "Learn Flexbox" },
    { "id": 30, "title": "Practice CSS Grid" },
    { "id": 31, "title": "Build a responsive page" },
    { "id": 32, "title": "Create a dark mode toggle" },
    { "id": 33, "title": "Learn React hooks" },
    { "id": 34, "title": "Use Context API" },
    { "id": 35, "title": "Practice Redux Toolkit" },
    { "id": 36, "title": "Implement authentication" },
    { "id": 37, "title": "Learn JWT authentication" },
    { "id": 38, "title": "Connect frontend to backend" },
    { "id": 39, "title": "Test API using Postman" },
    { "id": 40, "title": "Deploy app to Vercel" },
    { "id": 41, "title": "Deploy backend to Render" },
    { "id": 42, "title": "Configure environment variables" },
    { "id": 43, "title": "Write unit tests" },
    { "id": 44, "title": "Learn pytest basics" },
    { "id": 45, "title": "Debug application errors" },
    { "id": 46, "title": "Refactor old code" },
    { "id": 47, "title": "Practice Python OOP" },
    { "id": 48, "title": "Solve array problems" },
    { "id": 49, "title": "Solve linked list problems" },
    { "id": 50, "title": "Solve binary tree problems" },
    { "id": 51, "title": "Practice graph algorithms" },
    { "id": 52, "title": "Study dynamic programming" },
    { "id": 53, "title": "Learn recursion" },
    { "id": 54, "title": "Practice binary search" },
    { "id": 55, "title": "Review sorting algorithms" },
    { "id": 56, "title": "Read system design basics" },
    { "id": 57, "title": "Watch a tech conference talk" },
    { "id": 58, "title": "Learn Docker basics" },
    { "id": 59, "title": "Create a Docker container" },
    { "id": 60, "title": "Learn Kubernetes concepts" },
    { "id": 61, "title": "Practice Linux commands" },
    { "id": 62, "title": "Organize project folders" },
    { "id": 63, "title": "Backup important files" },
    { "id": 64, "title": "Clean desktop workspace" },
    { "id": 65, "title": "Check emails" },
    { "id": 66, "title": "Reply to pending messages" },
    { "id": 67, "title": "Plan tomorrow's schedule" },
    { "id": 68, "title": "Set weekly goals" },
    { "id": 69, "title": "Track daily expenses" },
    { "id": 70, "title": "Pay utility bills" },
    { "id": 71, "title": "Buy groceries" },
    { "id": 72, "title": "Prepare a healthy meal" },
    { "id": 73, "title": "Exercise for 30 minutes" },
    { "id": 74, "title": "Stretch after workout" },
    { "id": 75, "title": "Practice yoga" },
    { "id": 76, "title": "Drink enough water" },
    { "id": 77, "title": "Take a short break" },
    { "id": 78, "title": "Listen to a podcast" },
    { "id": 79, "title": "Watch an educational video" },
    { "id": 80, "title": "Learn a keyboard shortcut" },
    { "id": 81, "title": "Clean your room" },
    { "id": 82, "title": "Do the laundry" },
    { "id": 83, "title": "Water the plants" },
    { "id": 84, "title": "Organize your desk" },
    { "id": 85, "title": "Delete unnecessary files" },
    { "id": 86, "title": "Update software" },
    { "id": 87, "title": "Check computer security" },
    { "id": 88, "title": "Review monthly goals" },
    { "id": 89, "title": "Read a programming blog" },
    { "id": 90, "title": "Contribute to open source" },
    { "id": 91, "title": "Practice coding for one hour" },
    { "id": 92, "title": "Review interview questions" },
    { "id": 93, "title": "Update your resume" },
    { "id": 94, "title": "Apply for an internship" },
    { "id": 95, "title": "Network on LinkedIn" },
    { "id": 96, "title": "Learn an AI concept" },
    { "id": 97, "title": "Read about machine learning" },
    { "id": 98, "title": "Build a mini project" },
    { "id": 99, "title": "Reflect on today's progress" },
    { "id": 100, "title": "Sleep before 11 PM" }
]